name: bump
on:
  workflow_dispatch:

jobs:
  bump:
    name: increase version numbers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: npm install
        run:  npm ci   
      - name: bump version
        run: npm version patch -m "bump to %s"
      - name: git push
        run: git push origin 